// Generated by CoffeeScript 1.8.0
var VText, create, diff, patch;

create = require('virtual-dom/create-element');

diff = require('virtual-dom/diff');

patch = require('virtual-dom/patch');

VText = require('virtual-dom/vnode/vtext');

module.exports = function(component, state, parent) {
  var target, tree;
  tree = component(state);
  target = create(tree);
  return {
    target: target,
    mount: function() {
      return parent.appendChild(target);
    },
    update: function(state) {
      var newTree, patches;
      newTree = component(state);
      patches = diff(tree, newTree);
      target = patch(target, patches);
      return tree = newTree;
    },
    unmount: function() {
      return patch(target, diff(tree, new VText('')));
    }
  };
};
