// Generated by CoffeeScript 1.9.2
var component, extend;

extend = require('extend');

component = function(spec) {
  var Component, i, len, plugin, ref;
  spec = extend({}, spec);
  Component = function(state, params, hub) {
    return spec.render.call(spec, state, params, hub);
  };
  Component.use = function(plugin) {
    return plugin(Component, spec);
  };
  ref = component.plugins;
  for (i = 0, len = ref.length; i < len; i++) {
    plugin = ref[i];
    Component.use(plugin);
  }
  return Component;
};

component.plugins = [];

component.use = function(plugin) {
  return component.plugins.push(plugin);
};

module.exports = component;
