// Generated by CoffeeScript 1.8.0
var component, extend;

extend = require('extend');

component = function(spec) {
  var Component, plugin, _i, _len, _ref;
  spec = extend({}, spec);
  Component = function(state, params) {
    return spec.render.call(spec, state, params);
  };
  Component.use = function(plugin) {
    return plugin(Component, spec);
  };
  _ref = component.plugins;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    plugin = _ref[_i];
    Component.use(plugin);
  }
  return Component;
};

component.plugins = [];

component.use = function(plugin) {
  return component.plugins.push(plugin);
};

module.exports = component;
