// Generated by CoffeeScript 1.8.0
var Hook, compose, create, dom, extend, hook, widget;

create = require('virtual-dom/create-element');

compose = require('./compose');

widget = require('./widget');

extend = require('extend');

dom = require('virtual-dom/h');

Hook = (function() {
  function Hook(component, spec, state, options) {
    this.component = component;
    this.spec = spec;
    this.state = state;
    this.options = options;
  }

  Hook.prototype.type = 'Widget';

  Hook.prototype.create = function() {
    this.item = compose(this.component, this.state, this.el);
    if (this.spec.enter != null) {
      return this.spec.enter.call(this.spec, this.item, this.state, this.options);
    } else {
      return this.item.mount();
    }
  };

  Hook.prototype.remove = function() {
    if (this.spec.exit != null) {
      return this.spec.exit.call(this.spec, this.item, this.state, this.options);
    } else {
      return this.item.unmount();
    }
  };

  Hook.prototype.init = function() {
    this.el = create(dom('div'));
    setImmediate((function(_this) {
      return function() {
        return _this.create();
      };
    })(this));
    return this.el;
  };

  Hook.prototype.update = function(prev, el) {
    var olditem;
    if (prev.component === this.component) {
      if (this.component == null) {
        return el;
      }
      return el(this.item.update(this.state));
    }
    if (prev.component == null) {
      this.create();
      return el;
    }
    if (this.component == null) {
      this.remove();
      return el;
    }
    olditem = this.item;
    this.item = compose(this.component, this.state, el);
    if (this.spec.transition != null) {
      this.spec.transition.call(this.spec, olditem, this.item, this.state, this.options);
    } else {
      olditem.unmount();
      this.item.mount();
    }
    return el;
  };

  Hook.prototype.destroy = function() {
    return this.remove();
  };

  return Hook;

})();

hook = function(spec) {
  var Component, plugin, _i, _len, _ref;
  spec = extend({}, spec);
  Component = function(component, state, options) {
    return new Hook(component, spec, state, options);
  };
  Component.use = function(plugin) {
    return plugin(Component, spec);
  };
  _ref = hook.plugins;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    plugin = _ref[_i];
    Component.use(plugin);
  }
  return Component;
};

hook.plugins = [];

hook.use = function(plugin) {
  return hook.plugins.push(plugin);
};

module.exports = hook;
