// Generated by CoffeeScript 1.8.0
var compose, raf;

compose = require('./compose');

raf = require('raf');

module.exports = function(component, state) {
  var item, stateToApply, status;
  status = 'init';
  stateToApply = state;
  item = compose(component, state);
  stateToApply = null;
  return {
    status: status,
    target: item.target,
    update: function(state) {
      if (currentlyRedrawing) {
        throw new Error('State mutants are free');
      }
      if (stateToApply === null && status !== 'pending') {
        status = 'pending';
        stateToApply = state;
        return raf(function() {
          status = 'idle';
          if (stateToApply === null) {
            return;
          }
          status = 'rendering';
          item.update(stateToApply);
          stateToApply = null;
          return status = 'idle';
        });
      }
    },
    unmount: function() {
      return item.unmount();
    }
  };
};
