// Generated by CoffeeScript 1.9.2
module.exports = function(cache) {
  var _data;
  if (cache == null) {
    _data = {};
    cache = function() {
      return {
        get: function(key) {
          return _data[key];
        },
        set: function(key, value) {
          return _data[key] = value;
        }
      };
    };
  }
  return function(fn) {
    var _cache;
    _cache = cache();
    return function(state, params, hub) {
      var entry, key, slavehub;
      key = JSON.stringify([state, params]);
      entry = _cache.get(key);
      if (entry != null) {
        entry.hub = hub;
        return entry.vdom;
      }
      slavehub = {
        emit: function(m, p, cb) {
          return entry.hub.emit(m, p, cb);
        }
      };
      entry = {
        hub: hub,
        vdom: fn.call(this, state, params, slavehub)
      };
      _cache.set(key, entry);
      return entry.vdom;
    };
  };
};
