// Generated by CoffeeScript 1.8.0
var VText, create, diff, main, patch;

create = require('virtual-dom/create-element');

diff = require('virtual-dom/diff');

patch = require('virtual-dom/patch');

VText = require('virtual-dom/vnode/vtext');

main = require('main-loop');

require('setimmediate');

module.exports = function(component, spec) {
  return component.mount = function(el, state) {
    var scene, _render;
    _render = function(state) {
      return component(state);
    };
    scene = main(state, (function(state) {
      return _render(state);
    }), {
      create: create,
      diff: diff,
      patch: patch
    });
    el.appendChild(scene.target);
    return {
      update: function(state) {
        return setImmediate(function() {
          return scene.update(state);
        });
      },
      unmount: function() {
        _render = function() {
          return new VText('');
        };
        return scene.update({});
      }
    };
  };
};
