// Generated by CoffeeScript 1.8.0
var compose;

compose = require('./compose');

module.exports = function(component, spec) {
  return component.mount = function(el, state, params) {
    var scene;
    scene = compose(component, state, params, el);
    scene.mount();
    return {
      update: function(state, params) {
        return scene.update(state, params);
      },
      apply: function(state, params) {
        return scene.apply(state, params);
      },
      unmount: function() {
        return scene.unmount();
      }
    };
  };
};
