// Generated by CoffeeScript 1.8.0
var VText, Widget, component, createElement, diff, mainLoop, patch, stringify, widget;

createElement = require('virtual-dom/create-element');

diff = require('virtual-dom/diff');

patch = require('virtual-dom/patch');

VText = require('virtual-dom/vnode/vtext');

stringify = require('virtual-dom-stringify');

mainLoop = require('main-loop');

require('setimmediate');

component = function(spec) {
  var Component;
  Component = spec.render;
  Component.render = function(el, state) {
    var render, scene;
    render = function(state) {
      return Component(state);
    };
    scene = mainLoop(state, (function(state) {
      return render(state);
    }), {
      create: createElement,
      diff: diff,
      patch: patch
    });
    el.appendChild(scene.target);
    return {
      update: function(state) {
        return setImmediate(function() {
          return scene.update(state);
        });
      },
      remove: function() {
        render = function() {
          return new VText('');
        };
        return scene.update({});
      }
    };
  };
  Component.renderString = function(state) {
    return stringify(spec.render(state));
  };
  return Component;
};

Widget = (function() {
  function Widget(spec, state) {
    this.spec = spec;
    this.state = state;
  }

  Widget.prototype.type = 'Widget';

  Widget.prototype.init = function() {
    var dom;
    this.el = this.spec.render.call(this, this.state);
    dom = createElement(this.el);
    if (dom !== null) {
      this.el = dom;
    }
    setImmediate((function(_this) {
      return function() {
        if (_this.spec.afterMount != null) {
          return _this.spec.afterMount.call(_this, _this.el, _this.state);
        }
      };
    })(this));
    return this.el;
  };

  Widget.prototype.update = function(prev, el) {
    var k, v;
    for (k in prev) {
      v = prev[k];
      if (this[k] == null) {
        this[k] = v;
      }
    }
    if (this.spec.update != null) {
      return this.spec.update.call(this, el, this.state, prev);
    } else {
      return null;
    }
  };

  Widget.prototype.destroy = function(el) {
    if (this.spec.beforeUnmount != null) {
      return this.spec.beforeUnmount.call(this, el, this.state);
    }
  };

  return Widget;

})();

widget = function(spec) {
  return function(state) {
    return new Widget(spec, state);
  };
};

module.exports = {
  component: component,
  widget: widget,
  dom: require('virtual-dom/h'),
  svg: require('virtual-dom/virtual-hyperscript/svg'),
  partial: require('vdom-thunk')
};
