// Generated by CoffeeScript 1.8.0
var dedupe, extend;

extend = require('extend');

dedupe = function(query) {
  var q, result, _i, _len;
  result = {};
  if (query instanceof Array) {
    for (_i = 0, _len = query.length; _i < _len; _i++) {
      q = query[_i];
      extend(true, result, q);
    }
  } else {
    extend(true, result, query);
  }
  return result;
};

module.exports = function(component, spec) {
  return component.query = function(params) {
    if (spec.query == null) {
      return {};
    }
    return dedupe(spec.query.call(component, params));
  };
};
