// Generated by CoffeeScript 1.8.0
var stringify;

stringify = require('vdom-to-html');

module.exports = function(component, spec) {
  return component.stringify = function(state, params) {
    return stringify(spec.render.call(spec, state, params));
  };
};
