// Generated by CoffeeScript 1.8.0
var stringify;

stringify = require('virtual-dom-stringify');

module.exports = function(component, spec) {
  return component.renderString = function(state) {
    return stringify(spec.render.call(spec, state));
  };
};
