// Generated by CoffeeScript 1.9.2
var Thunk, thunk;

Thunk = (function() {
  function Thunk(render1, state1, params1, hub1) {
    this.render = render1;
    this.state = state1;
    this.params = params1;
    this.hub = hub1;
  }

  Thunk.prototype.type = 'Thunk';

  Thunk.prototype.render = function(previous) {
    return this.render.call(this, previous, this.state, this.params, this.hub);
  };

  return Thunk;

})();

thunk = function(render) {
  var Component, i, len, plugin, ref;
  Component = function(state, params, hub) {
    return new Thunk(render, state, params, hub);
  };
  Component.use = function(plugin) {
    return plugin(Component, render);
  };
  ref = thunk.plugins;
  for (i = 0, len = ref.length; i < len; i++) {
    plugin = ref[i];
    Component.use(plugin);
  }
  return Component;
};

thunk.plugins = [];

thunk.use = function(plugin) {
  return thunk.plugins.push(plugin);
};

thunk.Thunk = Thunk;

module.exports = thunk;
