// Generated by CoffeeScript 1.8.0
var Widget, create, extend, widget;

create = require('virtual-dom/create-element');

extend = require('extend');

Widget = (function() {
  function Widget(spec, state) {
    this.spec = spec;
    this.state = state;
  }

  Widget.prototype.type = 'Widget';

  Widget.prototype.init = function() {
    var dom;
    this.el = this.spec.render.call(this, this.state);
    dom = create(this.el);
    if (dom !== null) {
      this.el = dom;
    }
    setImmediate((function(_this) {
      return function() {
        if (_this.spec.afterMount != null) {
          return _this.spec.afterMount.call(_this, _this.el, _this.state);
        }
      };
    })(this));
    return this.el;
  };

  Widget.prototype.update = function(prev, el) {
    var dom, k, result, v;
    for (k in prev) {
      v = prev[k];
      if (this[k] === void 0) {
        this[k] = v;
      }
    }
    result = el;
    if (this.spec.update != null) {
      result = this.spec.update.call(this, el, this.state, prev);
      if (result !== null) {
        dom = create(result);
        if (dom !== null) {
          result = dom;
        }
      }
    }
    if (this.spec.onUpdate != null) {
      this.spec.onUpdate.call(this, result, this.state, prev);
    }
    return result;
  };

  Widget.prototype.destroy = function(el) {
    if (this.spec.beforeUnmount != null) {
      return this.spec.beforeUnmount.call(this, el, this.state);
    }
  };

  return Widget;

})();

widget = function(spec) {
  var Component, plugin, _i, _len, _ref;
  spec = extend({}, spec);
  Component = function(state) {
    return new Widget(spec, state);
  };
  Component.use = function(plugin) {
    return plugin(Component, spec);
  };
  _ref = widget.plugins;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    plugin = _ref[_i];
    Component.use(plugin);
  }
  return Component;
};

widget.plugins = [];

widget.use = function(plugin) {
  return widget.plugins.push(plugin);
};

widget.Widget = Widget;

module.exports = widget;
